name: Release

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test

    permissions:
      contents: read
      actions: read

    uses: ./.github/workflows/test.yaml

# Config for deploying the project goes here
