name: Test

on:
  pull_request:
  workflow_call:

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: read

    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Verify Docker is available
      - name: Verify Docker
        run: docker --version

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Run tests
        run: mvn clean test